name: Checks

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.26"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: uv sync --locked --all-extras
        working-directory: ./python
      - name: Run task
        run: |
          source ${{ github.workspace }}/python/.venv/bin/activate
          poe fmt --check
        working-directory: ./python

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.26"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: uv sync --locked --all-extras
        working-directory: ./python
      - name: Run task
        run: |
          source ${{ github.workspace }}/python/.venv/bin/activate
          poe lint
        working-directory: ./python

  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [
            "./packages/autogen-core",
            "./packages/autogen-magentic-one",
            "./packages/agbench",
            "./packages/autogen-ext",
            "./packages/autogen-agentchat",
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.26"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: uv sync --locked --all-extras
        working-directory: ./python
      - name: Run task
        run: |
          source ${{ github.workspace }}/python/.venv/bin/activate
          poe --directory ${{ matrix.package }} mypy
        working-directory: ./python

  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [
            "./packages/autogen-core",
            "./packages/autogen-magentic-one",
            "./packages/agbench",
            "./packages/autogen-ext",
            "./packages/autogen-agentchat",
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.26"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: uv sync --locked --all-extras
        working-directory: ./python
      - name: Run task
        run: |
          source ${{ github.workspace }}/python/.venv/bin/activate
          poe --directory ${{ matrix.package }} pyright
        working-directory: ./python
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          [
            "./packages/autogen-core",
            "./packages/autogen-magentic-one",
            "./packages/autogen-ext",
            "./packages/autogen-agentchat",
          ]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.26"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run uv sync
        run: |
          uv sync --locked --all-extras

        working-directory: ./python
      - name: Run task
        run: |
          source ${{ github.workspace }}/python/.venv/bin/activate
          poe --directory ${{ matrix.package }} test
        working-directory: ./python

  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ["./packages/autogen-core"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.26"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: uv sync --locked --all-extras
        working-directory: ./python
      - name: Run task
        run: |
          source ${{ github.workspace }}/python/.venv/bin/activate
          poe --directory ${{ matrix.package }} docs-check
        working-directory: ./python

  check-proto-changes-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          version: "0.4.26"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: uv sync --locked --all-extras
        working-directory: ./python
      - name: Run task
        run: |
          source ${{ github.workspace }}/python/.venv/bin/activate
          poe gen-proto
        working-directory: ./python
      - name: Check if there are uncommited changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: Process changes
        if: steps.changes.outputs.changed == 1
        run: echo "There are changes in the proto files. Please commit them."
